-- top.vhd — Vivado Top-Level for VGA Controller Port
-- Target: Artix-7 xc7a35tcpg236-1 (e.g. Digilent Basys3)
--
-- Differences vs. Quartus original:
--   PLL     : ALTPLL megafunction  →  Clocking Wizard IP  (clk_wiz_0)
--   ROM     : altsyncram           →  Block Memory Generator IP (blk_mem_gen_0)
--   Constraints: .sdc             →  .xdc
--   Simulation : ModelSim          →  xsim

library ieee;
use ieee.std_logic_1164.all;

entity top is
    port (
        clk_100mhz : in  std_logic;   -- 100 MHz on-board oscillator (Basys3 pin W5)
        reset      : in  std_logic;   -- Active-high push-button reset (BTN0)

        -- VGA connector
        hsync      : out std_logic;
        vsync      : out std_logic;
        vga_r      : out std_logic_vector(3 downto 0);
        vga_g      : out std_logic_vector(3 downto 0);
        vga_b      : out std_logic_vector(3 downto 0)
    );
end entity top;

architecture rtl of top is

    ---------------------------------------------------------------------------
    -- Clocking Wizard IP (generated by Vivado IP Catalog)
    --   Input  : 100 MHz  (clk_100mhz)
    --   Output : 25 MHz   (clk_25mhz)
    -- Generate via: Tools → Create IP → Clocking Wizard
    --   Board: xc7a35tcpg236-1, CLK_OUT1 = 25 MHz
    ---------------------------------------------------------------------------
    component clk_wiz_0 is
        port (
            clk_in1  : in  std_logic;
            clk_out1 : out std_logic;
            reset    : in  std_logic;
            locked   : out std_logic
        );
    end component clk_wiz_0;

    ---------------------------------------------------------------------------
    -- Internal signals
    ---------------------------------------------------------------------------
    signal clk_25mhz  : std_logic;
    signal pll_locked : std_logic;
    signal rst_sync   : std_logic;   -- synchronised reset to 25 MHz domain

    signal pixel_x    : std_logic_vector(9 downto 0);
    signal pixel_y    : std_logic_vector(9 downto 0);
    signal video_on   : std_logic;

begin

    ---------------------------------------------------------------------------
    -- 1. Clocking Wizard: 100 MHz → 25 MHz pixel clock
    ---------------------------------------------------------------------------
    u_clk : clk_wiz_0
        port map (
            clk_in1  => clk_100mhz,
            clk_out1 => clk_25mhz,
            reset    => reset,
            locked   => pll_locked
        );

    ---------------------------------------------------------------------------
    -- 2. Reset: hold until PLL locked AND external reset released
    ---------------------------------------------------------------------------
    rst_sync <= reset or (not pll_locked);

    ---------------------------------------------------------------------------
    -- 3. VGA timing generator
    ---------------------------------------------------------------------------
    u_vga : entity work.vga_controller
        port map (
            clk_25mhz => clk_25mhz,
            rst       => rst_sync,
            hsync     => hsync,
            vsync     => vsync,
            pixel_x   => pixel_x,
            pixel_y   => pixel_y,
            video_on  => video_on,
            red       => vga_r,
            green     => vga_g,
            blue      => vga_b
        );

end architecture rtl;
